### PR TITLE
FIX: Copy buttons, add node exporter, qol changes and fixes

### LINKED ISSUE #712: BUG: Prometheus' node_exporter isn't visible
**Describe the bug**
Right now there is no way to start/stop or manage the settings of node_exporter. Prometheus' node_exporter should be visible in "Service Plugins" and also have export mode, etc.

**To Reproduce**
Login, look at "Service Plugins"

**Expected behavior**
Prometheus' node_exporter visible as "Service Plugin"

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: node_exporter

### LINKED ISSUE #732: FR: List Number of Keys on Beaconchain
In Staking Page add Number of Keys on Node.

### LINKED ISSUE #800: BUG: can't copy validator key
**Describe the bug**
When clicking the button to copy the validator key to clipboard, nothing happens.

**To Reproduce**
1. Go to Staking page
2. Click on copy validator key
3. Try paste it somewhere

**Expected behavior**
validator key in the clipboard

**Desktop (please complete the following information):**
 - OS: MacOS
 - Launcher version `2.0.0-rc.4`

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: Staking page

### PR DESCRIPTION
**Pull request by NeoPlays**
## ToDo
- [x] fix #800
- [x] fix #712 
- [x] fix #732 
- [x] qol changes and fixes

### CODE REVIEW

File: launcher/src/components/UI/node-manage/ChangeConfirm.vue [hunk 1]
```diff
@@ -22,7 +22,7 @@
           <span>{{ item.content }}</span>
           <div class="right-icon">
             <img
-              src="../../../../public/img/icon/manage-node-icons/plugin-item-icon.png"
+              :src="item.service.sIcon"
```
Comment (maxbehzadi82) [inline launcher/src/components/UI/node-manage/ChangeConfirm.vue:25]: change it to item.service.icon

**Review by maxbehzadi82 — APPROVED** [review]
lg

**Review by maxbehzadi82 — APPROVED** [review]
lg

File: launcher/src/components/UI/node-manage/ChangeConfirm.vue (hunk 1 above)
Comment (NeoPlays) [reply launcher/src/components/UI/node-manage/ChangeConfirm.vue:25]: ok,
I just thought that they look very small and are very similar as well so it might be hard do differentiate.
