### PR TITLE
FIX: supporting sudo user

### LINKED ISSUE #510: Support super user setups
Right now working with a super user breaks the setup. Users should be able to use a super user instead of root to install & manage their node.

### PR DESCRIPTION
**Pull request by stefa2k**
fixes #510 

read up on the mechanics: https://unix.stackexchange.com/questions/175415/forward-function-and-variables-into-sudo-su-user-eof

### CODE REVIEW

File: launcher/src/backend/SSHService.js [hunk 1]
```diff
@@ -77,6 +79,16 @@ export class SSHService {
   }
 
   async exec (command, logline) {
+    const ensureSudoCommand = "sudo -u 'root' -i <<'=====EOF'\n" + command + "\n=====EOF"
+
+    return this.execCommand(ensureSudoCommand, logline)
+  }
+
+  async execCommand (command) {
+    return this.exec(command, command)
```
Comment (NeoPlays) [inline launcher/src/backend/SSHService.js:88]: shouldn't this be `return this.execCommand(command, command)`

**Review by NeoPlays — CHANGES_REQUESTED** [review]
