### PR TITLE
FIX: Escaping Problem of Passwords on Import

### LINKED ISSUE #2163: [Bug]: Password with special Chars fail when trying to import key
### Environment

Release

### Bug Description

- create keystore with a password that includes "`" for example.
- try to import it on staking page
- error

### PR DESCRIPTION
**Pull request by NeoPlays**
fixes #2163

### CODE REVIEW

File: launcher/src/backend/ValidatorAccountManager.js [hunk 1]
```diff
@@ -33,7 +33,13 @@ export class ValidatorAccountManager {
       }
       return readFileSync(file.path, { encoding: "utf8" });
     });
-
+    //escape all passwords for shell
+    passwords = passwords.map((p) => {
+      let pass = p;
+      if (pass.includes('"')) pass = pass.replaceAll(/"/g, '\\"');
```
Comment (gbayasgalan) [inline launcher/src/backend/ValidatorAccountManager.js:39]: Is it better to use a library to escape all potential special characters rather than manually escaping only some of them? For example: `require('shell-escape')`

Comment (NeoPlays) [reply launcher/src/backend/ValidatorAccountManager.js:39]: they're escaped by JSON.stringify. The main problem are the double and single quotes. And because JSON.stringify already does escaping i need to remove the extra `\` introduced with `'\''`. This was all more complex then i thought tbh 😅

Comment (NeoPlays) [reply launcher/src/backend/ValidatorAccountManager.js:39]: but i think there is another problem when the password includes `\`...

**Review by gbayasgalan — APPROVED** [review]
lgtm 🚀
