### PR TITLE
Fix: Display Server Package Updates Correctly in Update Panel

### LINKED ISSUE #1960: [Bug]: Server Updates in Update Panel shows no Package Updates
### Environment

Release

### Bug Description

The update panel does not show packages available for update for the server updates

image

### Launcher Version

2.2.1

### Operating System

Other

### Affected Service (if applicable)

--

### Logs (if applicable)

```shell
--
```

### Acknowledgment

- [X] I have checked the existing bugs and confirmed this issue is not already reported.

### PR DESCRIPTION
**Pull request by mabasian**
fix #1960

### CODE REVIEW

File: launcher/src/components/UI/base-header/components/modals/UpdatePanel.vue [hunk 1]
```diff
@@ -366,11 +366,11 @@ const searchOsUpdates = async () => {
 
 const getUpdatablePackagesCount = async () => {
   try {
-    const packagesCount = await ControlService.getCountOfUpdatableOSUpdate();
-    const numPackages = Number(packagesCount);
-    numberOfUpdatablePackages.value = isNaN(numPackages) || !numPackages ? 0 : numPackages;
+    const packages = await ControlService.getUpgradeablePackages();
```
Comment (NeoPlays) [inline launcher/src/components/UI/base-header/components/modals/UpdatePanel.vue:369]: if you're using `getUpgradeablePackages` you can directly save the statue in the pinia store so the ui doesn't need to load the data again: https://github.com/stereum-dev/ethereum-node/blob/main/launcher/src/components/UI/server-management/components/server-update/UpdateServer.vue#L164-L176

**Review by NeoPlays — CHANGES_REQUESTED** [review]

File: launcher/src/components/UI/base-header/components/modals/UpdatePanel.vue (hunk 1 above)
Comment (mabasian) [reply launcher/src/components/UI/base-header/components/modals/UpdatePanel.vue]: fixed

**Review by NeoPlays — APPROVED** [review]
lgtm 🚀
